stages:
  - build
  - test
  - docs
  - cianity_check

build_debug:
  stage: build
  image: "rust:1.96-slim-trixie"
  dependencies: []
  variables:
    RELEASE_FLAG: ""
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - cargo build $RELEASE_FLAG --workspace

build_release:
  stage: build
  image: "rust:1.96-slim-trixie"
  dependencies: []
  variables:
    RELEASE_FLAG: --release
  artifacts:
    paths:
      - target/release/cianity
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - cargo build $RELEASE_FLAG --workspace

test:
  stage: test
  image: "rust:1.96-trixie"
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - cargo nextest run --workspace

test.fmt:
  stage: test
  image: "rust:1.96-slim-trixie"
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy:
  stage: test
  image: "rust:1.96-slim-trixie"
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - rustup component add clippy
    - cargo clippy

build:
  stage: docs
  image: "rust:1.96-trixie"
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - curl -sL https://github.com/rust-lang/mdBook/releases/download/v0.5.4/mdbook-v0.5.4-x86_64-unknown-linux-gnu.tar.gz | tar zxf -
    - ./mdbook build docs

docs.fmt:
  stage: docs
  image: "rust:1.96-trixie"
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - curl -fsSL https://dprint.dev/install.sh | sh
    - $HOME/.dprint/bin/dprint check

check:
  stage: cianity_check
  image: "rust:1.96-trixie"
  dependencies:
    - build_release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - ./target/release/cianity check
    - ./target/release/cianity format --check
    - ./target/release/cianity build -t gitlab --check
