[package]
name = "ciane"
version = "0.1.0"
rust-version = "1.92.0"
edition = "2024"
authors = ["Hayden Stainsby <hds@caffeineconcepts.com>"]
readme = "README.md"
description = """
Parser for the ciane workflow language.
"""
license = "MIT"
repository = "https://github.com/hds/cianity"
categories = ["parser-implementations"]
keywords = ["ci", "ci/cd"]

[dependencies]
chumsky = "0.11"
ariadne = "0.6"
rowan = "0.16"
smol_str = "0.2"

[lints]
workspace = true
