[package]
name = "cianity-core"
version = "0.1.0"
rust-version = "1.92.0"
edition = "2024"
authors = ["Hayden Stainsby <hds@caffeineconcepts.com>"]
readme = "README.md"
description = """
Core check logic for the cianity CI workflow tool.
"""
license = "MIT"
repository = "https://github.com/hds/cianity"
categories = ["development-tools"]
keywords = ["ci", "ci/cd"]

[dependencies]
ciane = { path = "../ciane" }
ariadne = "0.6"
anyhow = "1"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
